name: bc-dot-com
recipe: drupal8
config:
  php: '7.3'
  webroot: 'web'
  # Optionally activate xdebug
  # xdebug: true
services:
  appserver:
    build:
      - "cd $LANDO_MOUNT && composer install"
tooling:
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
