name: bc-dot-com
recipe: drupal8
config:
  composer_version: 1-latest
  php: '7.3'
  webroot: 'web'
  # Optionally activate xdebug
  # xdebug: true
services:
  appserver:
    build:
      - chmod 0775 /app/web/sites/default
      - composer install
      - cp --force /app/conf/lando/settings.lando.php /app/web/sites/default/settings.local.php
tooling:
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
