name: bc-dot-com
recipe: drupal9
config:
  composer_version: 2-latest
  php: '7.4'
  webroot: 'web'
  # Optionally activate xdebug
  # xdebug: true
services:
  appserver:
    build:
      - composer install
      - bash conf/lando/setup.sh
tooling:
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
  update-settings:
    service: appserver
    cmd:
      - bash conf/lando/setup.sh
